### PR TITLE
add unicode support into Cell

### PR DESCRIPTION
**Pull request by askobara**
with tests

### CODE REVIEW

**Comment by phsym** [comment]
Cool, thanks for this. I'll upload this to crates.io as soon as I have time for it

**Comment by phsym** [comment]
Done. It's now available as version 0.1.2 in crates.io

**Comment by phsym** [comment]
Excuse my ignorance, I'm still learning Rust, but why do you use ```&cont[..]``` instead of just using ```cont```. I'm not sure about the aim of ```[..]``` here.

**Comment by askobara** [comment]
Thanks for update crates, I use the prettytable in my project :)

Oh, it's easier than you think!
In this context `cont` is `String` which have [ownership](http://doc.rust-lang.org/nightly/book/ownership.html), but for [UnicodeWidthStr::width](http://unicode-rs.github.io/unicode-width/unicode_width/trait.UnicodeWidthStr.html#tymethod.width) we needs only [borrowed](http://doc.rust-lang.org/nightly/book/references-and-borrowing.html) value with `str` type. So, operator `[..]` returns [slice](http://doc.rust-lang.org/nightly/collections/slice/index.html) (which don't have ownership) for our `String` or `str` in another words.
Also you can use operator `[..]` with your own boundaries, for example `[1..]` returs `str` without the first char and `[..4]` returns chunk from string with lenght = 4.
I hope I was able to explain this cool feature :) Feel free to ask if you have any question, I'm still learning Rust too :)

**Comment by phsym** [comment]
I'm glad you like prettytable. There's lot of room for improvements, so feel free to make suggestions, or other pull requests.

You answered my question, thanks. I was not aware I could use ```[..]``` on String to get the slice.
I would have use deref coercion with ```&cont as &str``` instead of ```&cont[..]``` but slice notation is much cleaner.

**Pull request merged**
