### PR TITLE
Reword README.md

### PR DESCRIPTION
**Pull request by hcpl**
- Use shorter and/or more precise sentences.
- Change code style.
- Expand and restructure examples.

---

- [x] Having a Table of Contents would be handy, README is too long now.
- [x] Should we use `try!` or `?` if the library code itself uses `try!` to fulfill the "support all Rust versions down to 1.9.0" objective (`?` requires Rust 1.13.0)?
- [ ] Does README need to be even more beginner-friendly?

### CODE REVIEW

**Comment by phsym** [comment]
Oh great ! I don't have time to review this tonight. I'll try to do it tomorrow. But I have no doubt it will be better than the original.

I'm fully agree with your 2 first proposals. And actually already thought many times about doing this:
* A table of content would be great for sure
* Cleaning up the code by switching from `try!` to `?`. In fact I have no objectives in supporting rust 1.9.0. I'm not sure many people are still using it. Also, I only run CI tests down to 1.9.0 only to be notified when compatibility is broken, and update the note about it in the README. So 1.13.0 would be good too.

Regarding your 3rd suggestion, I'm agree with it, but not sure how to do that

**Comment by hcpl** [comment]
- ToC is easy, I'll do it now.
- Stopping supporting old compilers can be seen as a breaking change by some versioning schemes. But having clean code is worth it.
- Many ways to do that, actually
  - Truncate README to essentials that 80% people expect at first sight from a "pretty table printing" library.
  - Move most of the README to GitHub wiki pages.
  - Provide an external resource that is easier to consume than GitHub-flavored Markdown, probably on github.io for an easy start.

**Comment by phsym** [comment]
Thanks for those improvements. Shall I merge ?

**Comment by hcpl** [comment]
Looks good to me now.

**Pull request merged**
