### PR TITLE
Reexporting types used from the term crate

### PR DESCRIPTION
**Pull request by hoodie**
This exports term types so that you don't have to use external types in your api

### CODE REVIEW

**Comment by hoodie** [comment]
@phsym would you agree that it's time to stop supporting 1.13 and 1.14?

**Comment by phsym** [comment]
@hoodie I do. All of this will be released in `0.8.0` so we can break a few things.

**Comment by phsym** [comment]
I think you can use the following syntax (or similar)
```rust
pub (crate) use ....;
```
in order to make an export publicly available  but only from the crate itself

**Comment by hoodie** [comment]
oops, actually we would have to retire every version up to 1.18.0
I guess that's still reasonable though

**Comment by phsym** [comment]
Dropping supoprt for rust releases prior to 1.18.0 is ok. The CI is much faster now 😄

**Comment by hoodie** [comment]
gentle reminder to release 0.7.0 already 😀
PLZ

**Comment by phsym** [comment]
Ooops. Now it's release. Sorry I'm quite busy this time :/

**Pull request merged**
