### PR TITLE
Converted all indentation tabs to 4 spaces

### LINKED ISSUE #53: Source code with tabs, rendered in documentation, looks ugly
Each tab is rendered 8 spaces wide.

For example, with 17 levels of indentation the whole builder steps block is shifted out of the screen (its 1366 pixels wide in my case): http://phsym.github.io/prettytable-rs/v0.6.6/src/prettytable/src/format.rs.html#275-283.

Some solutions:
- Use spaces instead of tabs
- Change rendering options in `rustdoc` to render tabs 4 spaces wide

P.S. Apparently, GitHub renders with 8 spaces too (https://github.com/phsym/prettytable-rs/blob/master/src/format.rs#L275-L283), so the first solution looks more viable to me now.

### PR DESCRIPTION
**Pull request by phsym**
Fixes #53

### CODE REVIEW

**Comment by phsym** [comment]
@hcpl Anything else I should change ?

**Comment by hcpl** [comment]
@phsym awesome, now fits into the code area on GitHub, looks good now!

All that is left to do is to update the docs, but docs are bound to crate releases, so I don't think there is a need to hurry.

**Comment by phsym** [comment]
@hcpl I just ran rustfmt on the code. I should have done that a long time ago. It's done now.
Now it just looks like a fresh new code I've never written :smile:

**Comment by hcpl** [comment]
@phsym now even better! Props to rustfmt :+1:

**Pull request merged**
